### ISSUE TITLE
merkle_tree_root may not be constrained

### ISSUE THREAD

**Issue by ebfull** [Zerocash/libzerocash#10]
`generate_r1cs_witness` takes a `merkle_tree_root` but doesn't do anything with it. This makes me wonder if it's actually constrained by anything?

**Comment by madars** [comment]
Yes, the Merkle tree root is constrained as follows:
- it is part of the circuit input: https://github.com/Zerocash/libzerocash/blob/master/zerocash_pour_ppzksnark/zerocash_pour_gadget.tcc#L60 and https://github.com/Zerocash/libzerocash/blob/master/zerocash_pour_ppzksnark/zerocash_pour_gadget.tcc#L447 ; and
- we generate constraints checking that each of the old coins is in a Merkle tree with root `merkle_tree_root`: https://github.com/Zerocash/libzerocash/blob/master/zerocash_pour_ppzksnark/zerocash_pour_gadget.tcc#L262 and https://github.com/Zerocash/libzerocash/blob/master/zerocash_pour_ppzksnark/zerocash_pour_gadget.tcc#L279 .

In the witness map, the Merkle tree root can be recomputed given leaf `old_coin_commitment_variables[i]` and the corresponding Merkle tree authentication path `old_coin_authentication_paths[i]` (consisting of O(log n) auxiliary hash values) by simply hashing bottom-up. In fact, this is what happens in `generate_r1cs_witness`: the Merkle tree root is recomputed inside.

When testing libzerocash, we had code that checked if the externally provided `merkle_tree_root` matches the one computed "inside" from `old_coin_commitment_variables[i]` and `old_coin_authentication_paths[i]`. When this debugging aid was removed, the interface still retained the "redundant" root.

Thanks for the good catch! I'll add back the checks as they might be useful for people who want to modify the internals of the Pour gadget.
