### ISSUE TITLE
Makefile default rules aren't sufficient for building .o's.

### ISSUE THREAD

**Issue by defuse** [Zerocash/libzerocash#2]
The `.o` files are built "magically" using make's default rules, i.e. `X.o` is built by looking for `X.cpp`. This doesn't work, because it doesn't capture the `X.cpp` files' dependencies on other headers, especially the template code.

The problem is that if you change one of the header files, or one of the template code files, and re-run make, it won't detect those changes and re-build. The workaround is to `make clean` every time you make a change.

**Comment by madars** [comment]
Indeed, if you change a template in `.hpp` or `.tcc` then compiler won't track this dependency via default make rules. `gcc -MMD` can help here by outputting dependencies appropriately. We do so in `libsnark` https://github.com/scipr-lab/libsnark/blob/master/Makefile#L194-L198 and the same solution should work for `libzerocash`.

I'll try to do push a similar patch to `libzerocash`'s `Makefile`.
